### ISSUE TITLE
Compatible with ROS2 Foxy bags?

### ISSUE THREAD

**Issue by sandman** [Kettenhoax/ros2bag_tools#15]
Is this package compatible with ROS2 Foxy bags? They have a .db3 (sqlite3) format.

**Comment by devrite** [comment]
Format wise yes, we just use the official APIs which support the stable format. Our package itself is only tested against rolling and to some degree humble. We recommend using it with rolling to access your bags.

**Comment by Kettenhoax** [comment]
This package works for any storage format (sqlite3), but we don't support a branch that is compatible with the rosbag2 API in the foxy distro.
To put it more simply, you can use ros2bag_tools **with a bag recorded in foxy**, but probably **not while using foxy**.
