### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by sandman** [Kettenhoax/ros2bag_tools#16]
I built the two packages in a ROS2 workspace and sourced the inlay. However when I run `ros2 bag sync --help`, I get the below error:
`Failed to load entry point 'sync': No module named 'rosbag2_py'
`

**Comment by devrite** [comment]
Have you installed all dependencies specified `package.xm`l? (See official ROS documentation on setting up worksapces and installing dependencies).

**Comment by Kettenhoax** [comment]
`rosbag2_py` is a declared dependency that is resolved when setting up the workspace.
You can read up on this at [docs.ros.org](https://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Creating-A-Workspace/Creating-A-Workspace.html#resolve-dependencies).
