### ISSUE TITLE
README read data frame example missing positional argument

### ISSUE THREAD

**Issue by vinnnyr** [Kettenhoax/ros2bag_tools#4]
When trying to follow the example in the README, I get the following traceback:
```
    dfs = read_data_frames(BagView(reader))
TypeError: read_data_frames() missing 1 required positional argument: &apos;field_dict&apos;
```

After a bit of investigation, it seems like it needs to have a dictionary passed in as well, see the test:

https://github.com/Kettenhoax/ros2bag_tools/blob/6877cb73549bb261b2f82efc5886a77bd6e8463a/rosbag2_tools/test/test_data_frame.py#L27

**Comment by Kettenhoax** [comment]
You're correct. Thanks for the notice! The README blocks needed updating anyways.
