### ISSUE TITLE
Small problem with error message

### ISSUE THREAD

**Issue by KeisukeShima** [Kettenhoax/ros2bag_tools#5]
Hello, thanks for providing a nice tool.
I found a small problem today and I would like to report here.

In `cut.py`, there is a place where it is not f-string.
https://github.com/Kettenhoax/ros2bag_tools/blob/master/ros2bag_tools/ros2bag_tools/filter/cut.py#L111

The solution is:
```python
                + f'duration of the input bags ({bag_start}, {bag_end})')
```

**Comment by Kettenhoax** [comment]
Good catch, thanks!
